// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "My App",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "My App",
            targets: ["AppModule"],
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/SwiftRex/SwiftRex.git", "0.8.8"..<"1.0.0"),
        .package(url: "https://github.com/SwiftRex/LoggerMiddleware.git", "0.3.9"..<"1.0.0"),
        .package(url: "https://github.com/teufelaudio/CombineRextensions.git", "0.1.8"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "CombineRex", package: "SwiftRex"),
                .product(name: "LoggerMiddleware", package: "LoggerMiddleware"),
                .product(name: "CombineRextensions", package: "CombineRextensions")
            ],
            path: "."
        )
    ]
)
